# Generated by Django 4.0.3 on 2022-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_text', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(to='organization.contact'),
        ),
    ]
